### ISSUE TITLE
 item 13: 使用立即调用的函数表达式创建新的作用域 (Use Immediately Invoked Function Expressions to Create Local Scopes)

### ISSUE THREAD

**Issue by mengyou658** [dreamapplehappy/effective-javascript#2]
这里不太理解，哪位大神能给说说呗，谢谢啦
查资料也不太明白，从哪里开始查

**Comment by mengyou658** [comment]
// 测试使用的数组
var testArr = [1, 2, 3];

// @3 使用闭包方式二
function generateFunc2(arr) {
    var result = [];
    var n = arr.length;
    for(var i = 0; i < n; i++) {
        (function() {
            result[i] = function() {
                return arr[i];
            }
        })()
    }
    return result;
}
// @3 产生新的函数
var g3 = generateFunc2(testArr);
console.log(g3[0]()); // 1
console.log(g3[1]()); // 2
console.log(g3[2]()); // 3
VM14910:19 undefined
VM14910:20 undefined
VM14910:21 undefined
undefined


chrome版本 54.0.2840.87 m (64-bit)

这里执行的结果跟上面说的不太一样啊

**Comment by dreamapplehappy** [comment]
@mengyou658 你很用心呀，是我写错了。正确的应该是下面这样的：
```javascript
function generateFunc2(arr) {
    var result = [];
    var n = arr.length;
    for(var i = 0; i < n; i++) {
        (function() {
            var j = i; // 少了这一部分，没有创建一个新的作用域和一个局部变量
            result[i] = function() {
                return arr[j]; // 这里使用j
            }
        })()
    }
    return result;
}
// ...
//var g3 = generateFunc1(testArr);
var g3 = generateFunc2(testArr);
```
谢谢啦！

**Comment by mengyou658** [comment]
也谢谢你
