### ISSUE TITLE
Chapter1-Itme4使用原始类型替代对象包裹有个问题

### ISSUE THREAD

**Issue by tangxiaolang101** [dreamapplehappy/effective-javascript#4]
str.someProperty = 'some';
在原始类型上面设置属性，在严格模式下是报错的，这种做法不是好的语法习惯。这个问题应该在说明里提一下，以免误导了新同学。
       谨上！

**Comment by dreamapplehappy** [comment]
@tangxiaolang101 谢谢，已经修改了。
